replicaCount: 1
pipeline: 
  secretval: set-me
  plainval: set-me
images:
  image: quay.io/maratoid/pipeline-demo:latest
  pullPolicy: IfNotPresent
service:
  name: busybox
  type: ClusterIP
  externalPort: 80
  internalPort: 80
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
